version: '3.4'

services:
  backend.web:
    image: ${DOCKER_REGISTRY-}backendweb
    build:
      context: .
      dockerfile: Backend.Web/Dockerfile
    ports:
    - 5000:80
  mongo:
    image: mongo
    ports:
    - "27017:27017"